### ISSUE TITLE
Is there a stable release of v1.2

### ISSUE THREAD

**Issue by smrgeoinfo** [sifrproject/MOD-Ontology#17]
is https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v1.2.owl a stable release?  If so, can it be put in a GitHub release or Tag so there is a stable location to link to for the ontology?  the tag or release should have equivalent versions in rdf/xml and ttl.

is http://www.isibang.ac.in the long term host for stewardship of the normative namespace, or is the namespace URI likely to change?

**Comment by biswanathdutta** [comment]
@smrgeoinfo uploaded the stable mod 1.2 in both rdf/xml and turtle format. 
The files are labeled as "stable." 

Regarding the namespace, we are exploring the possibility of transforming it to purl.org, or https://w3id.org/.  However, surely it is not going to happen soon. 

So, till then we are going to maintain the current namespace.

**Comment by smrgeoinfo** [comment]
@biswanathdutta Thanks.  Why don't you create a release using the GitHub release tools for the project (e.g. https://github.com/Esri/geoportal-server-catalog/releases)?

**Comment by biswanathdutta** [comment]
@smrgeoinfo thank you for pointing to the Github release tools. It is a valuable suggestion. We will do the necessary.
