### ISSUE TITLE
missing domain for some properties

### ISSUE THREAD

**Issue by nicholascar** [sifrproject/MOD-Ontology#29]
Are the following properties missing the `rdfs:domain` of `mod:Ontology`:

* `mod:metrics`
* `mod:numberOfDataProperties`
* `mod:numberOfObjectProperties`

The descriptions of these properties indicate that they are for use with the Ontology e.g. "The total number of object properties in an ontology", so I suspect their missing `rdfs:domain` is just an oversight.

**Comment by jonquet** [comment]
Hello. Good observation. 
This has been fixed in MOD2 where each metrics properties have rdfs:domain =>  mod:SemanticArtefactDistribution.
https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L2582
